### ISSUE TITLE
My friend is having trouble opening the program 

### ISSUE THREAD

**Issue by Dr-Kakashi** [misyaguziya/VRCT#13]
![VRCT Issue](https://github.com/misyaguziya/VRCT/assets/48993588/c9525df3-1150-4eb3-b1a8-715d326ba509)

Hi! My friend just downloaded VRCT and is having issues opening/running the program. I've attached an image so you can see what's happening. I have installed the program version 2.2.4 on Windows 11 and it works perfectly fine, so I tried to help her set up the program.

She has restarted her computer and followed the installation directions. When she opens the program it looks like it's hanging and is blank. We tried to search for an error log but can't find it. The log folder is empty. If you need it, could you tell us where to look? 

Here is her operating system and hardware specifications:
![VRCT Issue 2](https://github.com/misyaguziya/VRCT/assets/48993588/acace146-f302-48c8-a279-a4309f63f54c)
![VRCT Issue 3](https://github.com/misyaguziya/VRCT/assets/48993588/e6653abd-b6dc-41ce-ba87-08337693c5e1)

Update: 
Not sure if it's related, but just got an error.log that reads:

Traceback (most recent call last):
  File "main.py", line 10, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "config.py", line 1115, in <module>
  File "config.py", line 34, in __new__
  File "config.py", line 1100, in load_config
  File "config.py", line 270, in SELECTED_TAB_NO
  File "config.py", line 22, in saveJson
  File "json\__init__.py", line 293, in load
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Update 2: 
She decided to download older versions and version 1.3.2 is working for her. Version 2.0 and above does not work.

**Comment by ShiinaSakamoto** [comment]
[Update Report]
We actually don't know why this happens yet.
But we're working on developing a new program based on the web, so we hope it will solve that problem too.
We're changing the code from the ground up, so the release date is going to be quite a bit later, though...

**Comment by YukihoAA** [comment]
same in 2.2.7

**Comment by YukihoAA** [comment]
when i tried to run main.py, i've got error below

![image](https://github.com/user-attachments/assets/dd78f717-7698-4d44-89af-6a48eba43e4e)

**Comment by ShiinaSakamoto** [comment]
can you find that image,vrct_logo_mark_black.ico, in the directory (.......Desktop/VRCT/VRCT-2.2.7/img/) like the error says?

**Comment by YukihoAA** [comment]
yes there is ico files on paths

**Comment by YukihoAA** [comment]
it works fine after i reinstall windows

**Comment by ShiinaSakamoto** [comment]
Reinstall windows!? I think that must have been tough but umm, okay, that's good.

**Comment by misyaguziya** [comment]
@Dr-Kakashi 
The above problem may be cured by the change to WebUI in version 3.0.0.
Please check.
